---
- name: Configure DDoS mitigation
  hosts: all
  become: true

  vars:
    max_connections: 100
    max_connections_per_ip: 10
    syncookies_threshold: 100

  tasks:
    - name: Update and upgrade system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name:
          - iptables
          - iptables-persistent
          - fail2ban
          - nginx
        state: present

    - name: Configure sysctl for DDoS mitigation
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { key: "net.ipv4.tcp_syncookies", value: "1" }
        - { key: "net.ipv4.tcp_max_syn_backlog", value: "2048" }
        - { key: "net.ipv4.tcp_synack_retries", value: "2" }
        - { key: "net.ipv4.tcp_syn_retries", value: "5" }
        - { key: "net.ipv4.icmp_echo_ignore_broadcasts", value: "1" }
        - { key: "net.ipv4.icmp_ignore_bogus_error_responses", value: "1" }
        - { key: "net.ipv4.conf.all.accept_redirects", value: "0" }
        - { key: "net.ipv4.conf.default.accept_redirects", value: "0" }
        - { key: "net.ipv4.conf.all.secure_redirects", value: "0" }
        - { key: "net.ipv4.conf.default.secure_redirects", value: "0" }
        - { key: "net.ipv4.tcp_max_tw_buckets", value: "1440000" }
        - { key: "net.ipv4.tcp_fin_timeout", value: "15" }
        - { key: "net.ipv4.tcp_keepalive_time", value: "1800" }
        - { key: "net.ipv4.tcp_keepalive_probes", value: "5" }
        - { key: "net.ipv4.tcp_keepalive_intvl", value: "15" }

    - name: Set up iptables rules
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      loop:
        - "22"    # SSH
        - "80"    # HTTP
        - "443"   # HTTPS

    - name: Set default policies
      iptables:
        chain: "{{ item }}"
        policy: DROP
      loop:
        - INPUT
        - FORWARD

    - name: Allow established connections
      iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: Rate limit incoming TCP connections
      iptables:
        chain: INPUT
        protocol: tcp
        match: tcp
        tcp_flags: 
          flags: FIN,SYN,RST,ACK
          flags_set: SYN
        jump: ACCEPT
        limit: "{{ max_connections_per_ip }}/second"
        limit_burst: "{{ max_connections }}"

    - name: Drop invalid packets
      iptables:
        chain: INPUT
        ctstate: INVALID
        jump: DROP

    - name: Save iptables rules
      command: netfilter-persistent save

    - name: Configure fail2ban
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [DEFAULT]
          bantime = 3600
          findtime = 600
          maxretry = 5

          [sshd]
          enabled = true

    - name: Restart fail2ban
      systemd:
        name: fail2ban
        state: restarted